# -*- mode: ruby -*-
# vi: set ft=ruby :


IP_MASTER1 = "192.168.1.280"
IP_WORKER1 = "192.168.1.281"


Vagrant.configure("2") do |config|
  # config.vm.box = "ubuntu/bionic64"
  config.vm.box = "../cluster_k8s_baseImage/cluster_k8s_baseImage_ubuntu_focal64.box"

  $default_network_interface = `ip route | grep -E "^default" | awk '{printf "%s", $5; exit 0}'`


# config.vm.network "public_network",  bridge: "#$default_network_interface" , ip: "192.168.1.180"
config.vm.provision "shell", path: "scripts/remove-lock.sh"
config.vm.provision "shell", path: "scripts/base_installs.sh"


  config.vm.define "vagrantclusterk8s-master" do |node|

    node.vm.provider "virtualbox" do |vb|
        vb.name = "vagrantclusterk8s-master"
        vb.memory = 2048
        vb.cpus = 2
    end

    node.vm.hostname = "vagrantclusterk8s-master"
    node.vm.network "public_network",  bridge: "#$default_network_interface" , ip: "192.168.1.180"
    node.vm.provision "install-master", type: "shell", :path => "scripts/install-master.sh", env: {"ip" => "192.168.1.180"}
    # node.vm.provision "install-master", type: "shell", :path => "scripts/install-master.sh", env: {"MASTER_IP" => "#{IP_MASTER1}", "POD_NW_CIDR" => "#{POD_NW_CIDR}"}

  end


  config.vm.define "vagrantclusterk8s-node1" do |node|

    node.vm.provider "virtualbox" do |vb|
        vb.name = "vagrantclusterk8s-node1"
        vb.memory = 1048
        vb.cpus = 2
    end

    node.vm.hostname = "vagrantclusterk8s-node1"
    node.vm.network "public_network",  bridge: "#$default_network_interface" , ip: "192.168.1.181"
    node.vm.provision "install-worker", type: "shell", :path => "scripts/install-worker.sh", env: {"ip" => "192.168.1.181"}

    # public_network
  end




  config.vm.define "vagrantclusterk8s-node2" do |node|

    node.vm.provider "virtualbox" do |vb|
        vb.name = "vagrantclusterk8s-node2"
        vb.memory = 2048
        vb.cpus = 2
    end

    node.vm.hostname = "vagrantclusterk8s-node2"
    node.vm.network "public_network",  bridge: "#$default_network_interface" , ip: "192.168.1.182"
    node.vm.provision "install-worker", type: "shell", :path => "scripts/install-worker.sh", env: {"ip" => "192.168.1.182"}

  end



end
