# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  # config.vm.box = "ubuntu/bionic64"
  # config.vm.box = "debian/stretch64"
  config.vm.box = "hashicorp/bionic64"

  $default_network_interface = `ip route | grep -E "^default" | awk '{printf "%s", $5; exit 0}'`

  # config.vm.network "public_network",  bridge: "#$default_network_interface" , ip: "192.168.1.180"
  config.vm.provision "shell", path: "scripts/solve_vagrant_lock_problem.sh"
  config.vm.provision "shell", path: "scripts/baseInstall.sh"
  config.vm.provision "shell", path: "scripts/remove-lock.sh"



end
